### PR TITLE
fix: do not match too many characters when removing sourceMappingURL …

### LINKED ISSUE #285: Syntax error: unexpected token: ':' when setting option inline to no-fallback
Hi!
This issue was already reported at webpack https://github.com/webpack/webpack/issues/11417 but it looks more like an issue with this loader.

- Operating System: Windows 10 Pro, Version 2004
- Node Version: 14.5.0
- NPM Version: 6.14.5
- webpack Version: 4.44.1
- worker-loader Version: 3.0.2

### Expected Behavior
To run the worker file without problems.

### Actual Behavior
I get `Syntax error: unexpected token: ':'` and the worker isn't executed.
The syntax error happens at the end of the file where the source map comments are inserted. Somehow the last line has no `//` prefixed.

### Code
Standard vue.js config with the rule added:

```js
{
  test: /\.worker\.js$/i,
  use: [
    /* config.module.rule('worker').use('worker-loader') */
    {
      loader: 'worker-loader',
      options: {
        inline: 'no-fallback'
      }
    }
  ]
}
```

### How Do We Reproduce?
I created a new vue.js project with @vue/cli using vue.js 2 and babel, everything else was deselected. With the worker-loader added and a simple worker script invoked from src/App.vue:

https://github.com/schl3ck/worker-loader-inline-no-fallback

### PR DESCRIPTION
**Pull request by schl3ck**
…comment

a sourceMappingURL comment may be created by another loader and this removes it again, but too many
characters are removed, thus uncommenting a different line that contains invalid javascript

Closes #285

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
See #285

### CODE REVIEW

**Review by evilebottnawi — COMMENTED** [review]
Can we add tests?

File: src/utils.js [hunk 1]
```diff
@@ -87,7 +87,7 @@ ${
 }
 
 // Matches only the last occurrence of sourceMappingURL
-const innerRegex = /\s*[#@]\s*sourceMappingURL\s*=\s*([^\s'"]*)\s*/;
+const innerRegex = /\s*[#@]\s*sourceMappingURL\s*=\s*((?:[^\s'"\\]|\\[^n])*(?:\\n)?)\s*/;
```
Comment (evilebottnawi) [inline src/utils.js:90]: `^n`? Looks it is invalid

Comment (schl3ck) [reply src/utils.js:90]: The idea was to match everything except all whitespace, quotes and `\n`, but not a backslash on its own. It works like a negative lookahead but consuming characters. Another possible solution would be `.*?(?=[\s'"]|\\n)(?:\\n)?`, which actually looks a lot more readable (instead of `(?:[^\s'"\\]|\\[^n])*(?:\\n)?`)

And I've just noticed that with the current regex the match wouldn't stop when it encounters a whitespace or quote after a backslash, but it would have done before. I'm pushing a fix.

Also the test will fail, if it is in a multiline comment. Thanks for not letting this slip past!

**Comment by schl3ck** [comment]
I don't know why the lint job fails. I've tested it at the `v3.0.2` tag and it faild there too just so you know.

**Comment by evilebottnawi** [comment]
@schl3ck All fine, don't worry, I will look at this in near future
